### ISSUE TITLE
[Question] Blacklisting?

### ISSUE THREAD

**Issue by GeorgeWillaman** [LinusU/server-accepts-email#25]
Hey,
Just have to start off by saying thank you Linus for this, been looking for something similar to this for a while now!
Anyhow, due to the smaller nature of this repo and no issues, I just thought I'd ask this question here.
Can you recommend any good methods to practice to avoid blacklisting (going through a list of ~10k emails)?
Also, if I was to use a rotating proxy service, is there a published average as to how many SMTP server checks == blacklisting?
Thanks,
-G

**Comment by LinusU** [comment]
Hmm, I've used this with a very large number of emails, but not more than about ~10 emails per domain, and didn't have any problems. What is your use case?

**Comment by GeorgeWillaman** [comment]
Yep, that is about no more than I am going to do (permutations of a lead @ a company).
I was just curious, I couldn't find much info (I'm probably being blind and missing it!).
Thanks, Linus! 👍

**Comment by LinusU** [comment]
No worries, good luck!

for the record, we were running this from AWS with one of their standard IP addresses
